apiVersion: v1
kind: Service
metadata: 
  name: service-lb-demo
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: service-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006